create_postGraduate_word_path: D:\atFile\score\湖北工业大学本专科成绩模板.doc
export_postGraduate_word_path: D:\atFile\exportFile\postGraduate
pdf_postGraduate_path: D:\atFile\pdf\postGraduate\

mybatis-plus:
  global-config:
    db-config:
      id-type: auto #数据库主键自增


spring:
  redis:
    database: 0
    host: 127.0.0.1         # Redis服务器地址
    port: 6379              # Redis服务器连接端口
    password: redis         # Redis服务器连接密码（默认为空）
    pool:
      max-active: 200       # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 10          # 连接池中的最大空闲连接
      max-wait: -1          # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 0           # 连接池中的最小空闲连接
    timeout: 30000           # 连接超时时间（毫秒）
  mail:
    #邮件协议smtp
    host: smtp.qq.com
    port: 465
    #发送者的邮件的用户名
    username: 1264301139@qq.com
    #使用的编码
    default-encoding: utf-8
    #移动端客户授权码(在邮箱中设置)
    password: hxlqyuchnqshjhfg
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
    